### ISSUE TITLE
值得鼓励，加油！

### ISSUE THREAD

**Issue by yang123guo** [ChenXiaoSong12321/fe-summary#1]
谢谢

**Comment by ChenXiaoSong12321** [comment]
谢谢，请问你是从什么渠道找到这个仓库的呢？

**Comment by ChenXiaoSong12321** [comment]
> 谢谢

谢谢，请问你是从什么渠道找到这个仓库的呢？

**Comment by yang123guo** [comment]
https://www.lizenghai.com/archives/66272.html

**Comment by ChenXiaoSong12321** [comment]
好的，知道了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "faith"<notifications@github.com&gt;; 
发送时间: 2020年4月29日(星期三) 中午11:29
收件人: "ChenXiaoSong12321/fe-summary"<fe-summary@noreply.github.com&gt;; 
抄送: "陈世松"<448216252@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [ChenXiaoSong12321/fe-summary] 值得鼓励，加油！ (#1)





 
https://www.lizenghai.com/archives/66272.html
